src/Web/Models/ErrorViewModel.cs
namespace Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/Web/Models/ProductEntity.cs
namespace Web.Models;

public class ProductEntity
{
    public int id { get; set; }
    public string Product { get; set; }
    public long Rate { get; set; }
    public long Quantity { get; set; }
    public string ImagePath { get; set; }
}

src/Web/Controllers/CheckOutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.Models;
using Stripe.Checkout;

namespace Web.Controllers
{
    public class CheckOutController : Controller
    {
        private readonly ILogger<CheckOutController> _logger;

        public CheckOutController(ILogger<CheckOutController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<ProductEntity> productList = new List<ProductEntity>();

            productList = new List<ProductEntity>
            {
                new ProductEntity
                {
                    Product = "Some Product",
                    Rate = 1500,
                    Quantity = 2,
                    ImagePath = "img/kandinsky-download-1695369327830.png"
                },
                 new ProductEntity
                {
                    Product = "Some Test",
                    Rate = 1700,
                    Quantity = 7,
                    ImagePath = "img/kandinsky-download-1695369579241.png"
                },
                 new ProductEntity
                {
                    Product = "Test Product",
                    Rate = 2332,
                    Quantity = 23,
                    ImagePath = "img/kandinsky-download-1695369768994.png"
                }
            };
            return View(productList);
        }


        public IActionResult OrderConfirmation()
        {
            var service = new SessionService();

            Session session = service.Get(TempData["Session"].ToString());

            if (session.PaymentStatus == "paid")
            {
                var transaction = session.PaymentIntentId.ToString();

                return View("Success");
            }
            return View("Login");
        }

        public IActionResult Success()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult CheckOut()
        {
            List<ProductEntity> productList = new List<ProductEntity>();

            productList = new List<ProductEntity>
            {
                new ProductEntity
                {
                    Product = "Some Product",
                    Rate = 1500,
                    Quantity = 2,
                    ImagePath = "img/kandinsky-download-1695369327830.png"
                },
                 new ProductEntity
                {
                    Product = "Some Test",
                    Rate = 1700,
                    Quantity = 7,
                    ImagePath = "img/kandinsky-download-1695369579241.png"
                },
                 new ProductEntity
                {
                    Product = "Test Product",
                    Rate = 2332,
                    Quantity = 23,
                    ImagePath = "img/kandinsky-download-1695369768994.png"
                }
            };

            var domain = "http://localhost:7176/";

            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"CheckOut/OrderConfirmation",
                CancelUrl = domain + $"CheckOut/Login",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                CustomerEmail = "test@mail.com"
            };

            foreach (var item in productList)
            {
                var sessionListItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Rate * item.Quantity),
                        Currency = "inr",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.ToString(),
                        }
                    },
                    Quantity = item.Quantity
                };

                options.LineItems.Add(sessionListItem);
            }
            var service = new SessionService();
            Session session = service.Create(options);

            TempData["Session"] = session.Id;

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }
    }
}

src/Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Web/Views/CheckOut/Index.cshtml
@model IEnumerable<ProductEntity>

<br />

<table class="table tabler-reponsive table-light table-bortered" style="width:100%;">
    <tr>
        <th>Product Name</th>
        <th>Rate</th>
        <th>Quantity</th>
        <th>Product Image</th>
        <th>Total</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Product</td>
            <td>@item.Rate</td>
            <td>@item.Quantity</td>
            <td><img src="@item.ImagePath" style="width:150px; height:150px;" /></td>
            <td>@(item.Rate * item.Quantity)</td>
        </tr>
    }
</table>

<br />
<p>
    <a asp-action="Checkout" asp-controller="CheckOut" value="CheckOut">CheckOut</a>
</p>

src/Web/Views/CheckOut/Login.cshtml
<div class="container row">
    <div class="col-12 text-center">
        <h2 class="text-primary text-center">Ooops!</h2>
        <br /><br />
        <img src="~/img/kandinsky-download-1689233206284.png" width="25%"/>
    </div>
    <h3 class="col-12 text-center" style="color: darkmagenta;">
        <br />
        Thanks for shopping this FCK Cats
        <br />
    </h3>
</div>

src/Web/Views/CheckOut/Success.cshtml
<div class="container row">
    <div class="col-12 text-center">
        <h2 class="text-primary text-center">Order Placed Successfully!</h2>
        <br /><br />
        <img src="~/img/kandinsky-download-1689233206284.png" width="25%"/>
    </div>
    <h3 class="col-12 text-center" style="color: darkmagenta;">
        <br />
        Thanks for shopping this FCK Cats
        <br />
    </h3>
</div>

src/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="CheckOut" asp-action="Index">Stipe Demo Cats</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CheckOut" asp-action="Index">Cats Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>